@startuml code_charts
' skinparam backgroundColor transparent
'() System #DA70D5
top to bottom direction

' --- TUTORIAL ---
abstract Tutorial<t: TutorialType> {
  - t: TutorialType
  __public method__
  + start() : void
  __private methods__
  - getConfigState() : boolean
  - setConfigState(state: boolean) : void
  - show() : boolean
  __abstract methods__
  - {abstract} tutorial() : void
}

enum TutorialType {
  ZOOM
  EYETRACKING
  CODECHARTS
}

' Notes
note right of Tutorial::start
    Startet Tutorial, beinhaltet interne Aufrufe
end note
note right of Tutorial::getConfigState
    Sendet eine Anfrage an das Config-Modul,
    abhängig vom Typ des Tutorials
end note
note right of Tutorial::tutorial
    Beinhaltet eigentliche Implementierung der Tutorials
end note

' Interaktionen
Tutorial::t -l- TutorialType
Tutorial -d- Config


' --- BILD ---

abstract Bild {
  + load(url: String) : void
  + show() : void
}

' === CODE CHARTS ===
package CodeCharts {

    ' CodeCharts Tutorial 
    class CodeChartsTutorial {
      - t: TutorialType
      __public method__
      + start() : void
      __private methods__
      - getConfigState() : boolean
      - setConfigState(state: boolean) : void
      - show() : boolean
      __abstract methods__
      - {abstract} tutorial() : void
    }
  
    ' CodeCharts Coordinator
    class CodeChartsCoordinator {
        - speed: float[2]
        - isTutorial: boolean
        - isRelative: boolean
        - dimensions: int[2]
        - strings: String[..]
        __public method__
        + startCodeCharts() : void
        __private methods__
        - loadConfigData() : boolean
        - tryTutorial() : void
    }

    ' Notes
    note left of CodeChartsCoordinator::speed
        speichert Wechselzeit zw. Bild-Raster-Eingabefenster
    end note
    note left of CodeChartsCoordinator::isRelative
        speichert ob das Rater relativ oder feste Größe hat
    end note
    note left of CodeChartsCoordinator::strings
        speichert Liste der Stings für Raster
    end note
    note left of CodeChartsCoordinator::startCodeCharts
        ruft tryTutorial auf & steuert die Anzeige von Bi. Ra. und Ei.
    end note
    note left of CodeChartsCoordinator::loadConfigData
        sendet initiale Daten an andere Klassen
    end note
    

    ' CodeCharts Interner Speicher
    class CodeChartsInternerSpeicher {
        __public method__
        + addPic(url: String) : void
        + addSizeAndCord(size: int[2], coordinates: int[2]) : void
        + saveData() : boolean
    }

    ' Notes
    note left of CodeChartsInternerSpeicher::addPic
        Speichert URL des Bildes
    end note
    note left of CodeChartsInternerSpeicher::addSizeAndCord
        Speichert Rastergröße & Koordinate des eingegebenen Strings
    end note
    note left of CodeChartsInternerSpeicher::saveData
        sendet alle Durchläufe an Speichermedium
    end note

    ' CodeCharts Bild
    class CodeChartsBild {
        + load(url: String) : void
        + show() : void
    }

    ' Notes
    note right of CodeChartsBild::load
        Unsicher ob es sinnvoll ist das Bild vorzuladen
    end note

    ' CodeCharts Raster
    class CodeChartsRaster {
        ' Unsicher ob es sinnvoll ist alle vorherigen Durchläufe auf einmal zu laden
        - dimensions: int[2]
        - strings: String[..]
        - coords: int[2]
        __public method__ 
        + setInput(input: String): void
        + setData(dimensions: int[2], strings: String[..]): void
        + show() : void
        + calculate() : void
        __private methods__
        - loadPastRuns() : void
        - sendData() : void
    }

    ' Notes
    note right of CodeChartsRaster
        zeigt Raster an, berechnet dieses und die Koordinate des Strings
    end note
    note left of CodeChartsRaster::calculate
        berrechnet Koordinaten und Raster
    end note
    note left of CodeChartsRaster::loadPastRuns
        holt die vorherigen Durchläufe aus Interner Speicher zur Berechnung d. Rasters 
    end note
    note left of CodeChartsRaster::sendData
        sendet Daten des Duchlaufs an Interner Speicher
    end note

    ' CodeCharts Eingabefenster
    class CodeChartsEingabefenster {
        __public method__
        + show() : String
        __private methods__
        - checkButton() : boolean
        - validateString(input: String): boolean
        - ErrorMessage() : void
    }

    ' Notes
    note left of CodeChartsEingabefenster::checkButton
        überprüft ob Eingabe bestätigt wurde
    end note
    note left of CodeChartsEingabefenster::validateString
        überprüft die Richtigkeit der Eingabe anhand der Strings-Liste
    end note
    note left of CodeChartsEingabefenster::ErrorMessage
        gibt Fehlermeldung aus wenn falscher String eingegeben
    end note


    ' Vererbungen
    Bild <|-d- CodeChartsBild
    Tutorial <|-d- CodeChartsTutorial

    ' Interaktionen
    CodeChartsCoordinator -- CodeChartsBild : > send initial data and show
    CodeChartsCoordinator -- CodeChartsRaster : > send initial data and show
    CodeChartsCoordinator::startCodeCharts -- CodeChartsEingabefenster : > show
    CodeChartsCoordinator::loadConfigData -- CodeChartsInternerSpeicher : > send picture
    CodeChartsCoordinator::tryTutorial -- CodeChartsTutorial : > start Tutorial?
    CodeChartsRaster -- CodeChartsInternerSpeicher : < load data
    CodeChartsRaster -- CodeChartsInternerSpeicher : > save data
    CodeChartsEingabefenster -- CodeChartsRaster : > send Input



    ' Andere Module
    CodeChartsInternerSpeicher::saveData -- SpeicherMedium : > saves Data
    CodeChartsCoordinator::startCodeCharts -- Config : < gets Initial Data
  
}

' Blackboxen / Andere Module
package Config {}

package SpeicherMedium {}

@enduml