@startuml code_charts
' skinparam backgroundColor transparent
'() System #DA70D5
top to bottom direction

' --- TUTORIAL ---
abstract Tutorial<t: TutorialType> {
  - t: TutorialType
  __public method__
  + start() : void
  __private methods__
  - getConfigState() : boolean
  - setConfigState(state: boolean) : void
  - show() : boolean
  __abstract methods__
  - {abstract} tutorial() : void
}

enum TutorialType {
  ZOOM
  EYETRACKING
  CODECHARTS
}

' Interaktionen
Tutorial::t -l- TutorialType
Tutorial -d- Config


' --- BILD ---

abstract Bild {
  + load(url: String) : void
  + show() : void
}

' === CODE CHARTS ===
package CodeCharts {

    ' CodeCharts Tutorial 
    class CodeChartsTutorial {
      - t: TutorialType
      __public method__
      + start() : void
      __private methods__
      - getConfigState() : boolean
      - setConfigState(state: boolean) : void
      - show() : boolean
      __abstract methods__
      - {abstract} tutorial() : void
    }
  
    ' CodeCharts Coordinator
    class CodeChartsCoordinator {
        - speed: float[2]
        - isTutorial: boolean
        - isRelative: boolean
        - dimensions: int[2]
        - strings: String[..]
        __public method__
        + startCodeCharts() : void
        __private methods__
        - loadConfigData() : boolean
        - tryTutorial() : void
    }

    ' CodeCharts Interner Speicher
    class CodeChartsInternerSpeicher {
        __public method__
        + addPic(pic: unknown) : void
        + addSizeAndKord(size: int[2], coordinates: int[2]) : void
        + saveData() : boolean
    }

    ' CodeCharts Bild
    class CodeChartsBild {
        ' Unsicher ob es sinnvoll ist das Bild vorzuladen
        + load(url: String) : void
        + show() : void
    }

    ' CodeCharts Raster
    class CodeChartsRaster {
        ' Unsicher ob es sinnvoll ist alle vorherigen Durchläufe auf einmal zu laden
        - dimensions: int[2]
        - strings: String[..]
        - kords: int[2]
        __public method__ 
        + setData(dimensions: int[2], strings: String[..]):void
        + show() : void
        + calculate() : void
        __private methods__
        - loadPastRuns() : void
        - sendData() : void
    }

    ' CodeCharts Eingabefenster
    class CodeChartsEingabefenster {
        __public method__
        + show() : String
        __private methods__
        - checkButton() : boolean
        - validateString(input: String): boolean
        - ErrorMessage() : void
    }


    ' Vererbungen
    Bild <|-d- CodeChartsBild
    Tutorial <|-d- CodeChartsTutorial

    ' Interaktionen
    ' Bild & Raster mehrere Anbindungen (startCodeCharts, loadConfigData)
    CodeChartsCoordinator: -- CodeChartsBild : >
    CodeChartsCoordinator: -- CodeChartsRaster : >
    CodeChartsCoordinator::startCodeCharts -- CodeChartsEingabefenster : >
    CodeChartsCoordinator::tryTutorial -- CodeChartsTutorial : >
    ' load & send Kante?
    CodeChartsRaster -- CodeChartsInternerSpeicher : < >
    CodeChartsEingabefenster -- CodeChartsRaster : >



    ' Andere Module
    CodeChartsInternerSpeicher::saveData -- SpeicherMedium : > saves Data
    ' von startCodeCharts oder von loadConfigData
    CodeChartsCoordinator::startCodeCharts -- Config : < gets Initial Data
  
}

' Blackboxen / Andere Module
package Config {}

package SpeicherMedium {}

@enduml