@startuml CodeCharts
' left to right direction

actor Testperson as t
actor Forschende as f

rectangle CodeCharts as z #789dd5 {
    usecase "Tutorial anschauen" as td
    usecase "Tutorial: zukünftige Sichtbarkeit wählen" as tw
    usecase "Bild betrachten" as bb
    usecase "Raster betrachten" as rb
    usecase "Eingabe tätigen" as et
    usecase "Error-Message or Falsche Eingabe" as em
}

rectangle AnalyseClient as a {
    usecase "Ergebnisse anschauen" as ea
}

rectangle Config as c {
    usecase "Einstellungen setzen" as es
    usecase "Tutorialeinstellung ändern" as tä
}

' Testperson
t --> td
t --> tw
t --> bb
t --> rb
t --> et
t --> em

' Forschende
es <-- f
ea <-- f

' intern
tw ..> tä : <<included>> 
z <.. a : <<extended>> über Speichermedium
z ..> c : <<included>> Versuchseinstellungen abfragen
td ..> tw : <<included>>
bb ..> rb : <<included>>
rb ..> et : << included ? >>
em ..> et : <<excluded>> 


@enduml
