@startuml zoommaps

abstract Bild
abstract Tutorial

package ZoomMaps {
  class ZoomTutorial {

  }

  class ZoomInput {
  }

  class ZoomCalculator {
  }

  class ZoomBild {

  }
  
}

package SpeicherMedium {}

package Config {}

' Vererbungen
Bild <|-- ZoomBild
Tutorial <|-- ZoomTutorial

' Interaktionen
ZoomInput -- ZoomCalculator
ZoomCalculator -- ZoomBild

' Andere Module
ZoomCalculator -- SpeicherMedium
ZoomCalculator -- Config
@enduml
