@startuml speichermedium
' === Speichermedium ===
package Speichermedium {
      ' SpeicherUtilities
      class SpeicherUtilities {
         - Location: String
         __public method__
         + deleteData(data_client_input: String) : void
         + searchData(data_client_input: String) : Data
         + saveData(data: Data) : void
         + setLocation(config_input: String) : void
         + getLocation() : void
     }

      class Data {
         + type: SpeicherType
         + data: unknown
         + config_id: int
      }

      note right of Data
         Beinhaltet dann die Struktur/Variablen für die verschiedenen Daten, 
         die abgespeichert werden
      end note

      ' SpeicherType
      enum SpeicherType {
         ZOOM
         EYETRACKING
         CODECHARTS
      }

      ' Interaktionen
      SpeicherType -- Data::type
      Data -- SpeicherUtilities

     ' Andere Module
     SpeicherUtilities::Location -- Config : < Location
     SpeicherUtilities::saveData -- CodeCharts : < Data
     SpeicherUtilities::saveData -- ZoomMaps : < Data
     SpeicherUtilities::saveData -- EyeTracking : < Data
     SpeicherUtilities -- AnalyseClient
}


' Blackboxen / Andere Module
 package Config {}

 package CodeCharts {}

 package ZoomMaps {}

 package EyeTracking {}

 package AnalyseClient {}

@enduml
