@startuml speichermedium
' === Speichermedium ===
package Speichermedium {
      ' SpeicherUtilities
      class SpeicherUtilities {
         - Location: String
         __public method__
         + deleteData(data_client_input: String) : void
         + searchData(data_client_input: String) : Data
         + saveData(data: Data) : void
         + setLocation(config_input: String) : void
         + getLocation() : void
     }

      

     ' Andere Module
     SpeicherUtilities::Location -- Config : < Location
     SpeicherUtilities::saveData -- CodeCharts : < Data
     SpeicherUtilities::saveData -- ZoomMaps : < Data
     SpeicherUtilities::saveData -- EyeTracking : < Data
     SpeicherUtilities -- AnalyseClient
}

package Util {

class Data<t: ToolType> {
         + t: ToolType
         + data: unknown
         + config_id: int
     }

note right of Data
   Beinhaltet dann die Struktur/Variablen für die verschiedenen Daten, 
   die abgespeichert werden
end note

      

' Interaktionen
      
Data -- SpeicherUtilities
ToolType -- Data::type

' ToolType
      enum ToolType {
       ZOOM
       EYETRACKING
       CODECHARTS
     }

}
' Blackboxen / Andere Module
 package Config {}

 package CodeCharts {}

 package ZoomMaps {}

 package EyeTracking {}

 package AnalyseClient {}

@enduml
