@startuml analyseclient

' === ANALYSE CLIENT ===
package Analyse-Client{
  
  ' Client
  class Client {
    - data: Data
    - dataForComp: Data
    - analyseTypes: Types
    - analyzedData: List<String>
    __public methods__
    + getData(start: Date, end: Date, dataType: ToolType): boolean
    + getDataForComp(start: Date, end: Date, dataType: ToolType): boolean
    + setAnalyseTypes(): boolean
    + analyseData(): boolean
    + displayAnalyzedData(): void
    + export(): boolean
  }

  ' Analyse
  abstract Analyse {
    - calcRelFreq(data: Data): List<List<Float>>
    - createTimeTable(data: Data): List<List<Float>>
  }

  ' Heatmap
  class Heatmap {
    - heatmap: List<List<Float>>
    __public methods__
    + createHeatmap(data: Data): String
    + compHeatmaps(otherHeatmap: Heatmap): String
  }

  ' Verlauf
  class Verlauf {
    __public method__
    + createVerlauf(data: Data): String
    __private method__
    - drawDiagramm(diagrammData: List<List<Float>>): String
  }

  ' Diagramm
  class Diagramm {
    __public methods__
    + createRelFreqImgArea(data: Data): String
    + createViewTimeDistr(data: Data): String
    __private method__
    - calcViewTimeDistr(): float[4]
    - drawDiagramm(diagrammData: float[4], type: int): String
  }

  ' Types
  class Types {
    - heatmap: boolean
    - compHeatmap: boolean
    - verlauf: boolean
    - relFrqImgArea: boolean
    - viewTimeDistr: boolean
    __public methods__
    + Types(heatmap: boolean, compHeatmap: boolean, verlauf: boolean,
     relFrqImgArea: boolean, viewTimeDistr: boolean)
    + getHeatmap(): boolean
    + getCompHeatmap(): boolean
    + getVerlauf(): boolean
    + getRelFrqImgArea(): boolean
    + getViewTimeDistr(): boolean
  }

  ' Typen der erhobenen Daten
  enum ToolType {
    ZOOM
    EYETRACKING
    CODECHARTS
  }

  ' Vererbung
  Analyse <|-u- Heatmap
  Analyse <|-u- Verlauf
  Analyse <|-u- Diagramm

  ' Interaktionen
  Client::getData -l- ToolType
  Client::getDataForComp -l- ToolType
  Client::analyseData -d- Heatmap 
  Client::analyseData -d- Verlauf
  Client::analyseData -d- Diagramm

  ' Andere Module
  Client::getData -u- SpeicherMedium : > gets Data
  Client::getDataForComp -u- SpeicherMedium : > gets Data
  Client::export -r- PCSpeicher : > save to

}
' Blackbox
package SpeicherMedium {}

package PCSpeicher {}

'package GUI {}

' Interaktion
'Client::displayAnalyzedData -l- GUI : > output

@enduml
