@startuml zoommaps
' skinparam backgroundColor transparent
() System #DA70D5
top to bottom direction

package Util {
    ' --- TUTORIAL ---
    abstract Tutorial<t: ToolType> {
      - t: ToolType
      __public method__
      + start() : void
      __private methods__
      - getConfigState() : boolean
      - setConfigState(state: boolean) : void
      - show() : boolean
      __abstract methods__
      - {abstract} tutorial() : void
    }

    enum ToolType {
      ZOOM
      EYETRACKING
      CODECHARTS
    }

    ' Notes
    note left of Tutorial::start
        Startet Tutorial, beinhaltet interne Aufrufe
    end note
    note left of Tutorial::getConfigState
        Sendet eine Anfrage an das Config-Modul,
        abhängig vom Typ des Tutorials
    end note
    note left of Tutorial::tutorial
        Beinhaltet eigentliche Implementierung der Tutorials
    end note

    ' Interaktionen
    Tutorial -u- ToolType
    Data -r- ToolType
    Tutorial -d- Config


    ' --- BILD ---

    abstract Bild {
        # location : String
        + Bild(url: String)
        + show() : void
        + hide() : void
    }

    class Data<t: ToolType> {
        + t: ToolType
        + data: unknown
        + config_id: int
    }
}



' === ZOOM MAPS ===
package ZoomMaps {

    ' Zoom Input
    class ZoomInput {
        - onClick() : void
        - onScroll() : void
    }

    ' Notiz
    note right of ZoomInput
        Kann sich noch ändern, je nachdem wie Schnittstelle zum System aussieht
    end note

    ' Zoom Tutorial
    class ZoomTutorial<t: ToolType> {
        - tutorial() : void
    }

    ' Zoom Calculator
    class ZoomCalculator {
        - speed: float
        - position: float[3]
        - data: Util.Data
        __public method__
        + processInput(raw_input: unknown) : void
        + save() : boolean
        __private methods__
        - calculate(raw_input: unknown) : float[3]
    }

    ' Notiz
    note right of ZoomCalculator
        Typ von raw_input noch unbekannt
    end note

    ' Zoom Bild
    class ZoomBild {
        + move(position: float[3]): float[3]
    }


    ' Vererbungen
    Bild <|-- ZoomBild
    Tutorial <|-- ZoomTutorial

    ' Interaktionen
    ZoomInput -d- ZoomCalculator
    ZoomCalculator  -u- ZoomBild : > moves

    ' Andere Module
    ZoomCalculator -- SpeicherMedium : > saves Data
    ZoomCalculator -l- Config : < speed
    ZoomInput -u- System : > listens to

}

' Blackboxen / Andere Module
package Config {}

package SpeicherMedium {}

@enduml
