@startuml
' skinparam backgroundColor transparent
() System #DA70D5
top to bottom direction


package Util {

   

  


    ' --- BILD ---

    abstract Bild {
      + load(url: String) : void
      + show() : void
    }

  
}


' === EYETRACKING ===
package EYETRACKING {

    ' Auge
    class Auge {
        - input camera
        - get Eye() : void
        - get Pupil() : void
    }

    ' EytrackingBild
    class EytrackingBild {
        - width: int
        - height: int
        __
        + load grit
    }
  
    ' Setup
    class Setup {
        - distance: float
        - position: float
        - angle_from _Auge
        __private methods__
        - calculate(input_pupil: position, angle) : return coordinates
        - save_in_results(coordinates)
    }

    ' Results
    class Results {
        + save(position: x, y, time)
    }


    ' Vererbungen
    Results -- Setup
    Auge -- Setup
    EytrackingBild -- Setup
    Bild <|-- EytrackingBild
    

    

    ' Andere Module
    Results::save -- SpeicherMedium : > saves Data 
    EytrackingBild  -r- System : < screensize
    Auge -r- System : < cam
  
}

' Blackboxen / Andere Module



package SpeicherMedium {}
@enduml
