@startuml Datenanalyse Client

' Transitions
[*] -> InputAnalyseTypes: start Client (showClientGUI)
InputAnalyseTypes -d-> InputData: setAnalyseTypes()\n [analyseTypes.size != 0]
InputAnalyseTypes -> InputAnalyseTypes: setAnalyseTypes()\n [analysTypes.size == 0]
InputData -d-> WaitForSpeichermedium: getData()\n [start < end]\n AND [start & end = Date]\n AND [dataType.size == 1]
InputData -> InputData: getData()\n [start > end]\n OR [start OR end != Date]\n OR [dataType.size != 1]
WaitForSpeichermedium -> InputData: [data == null]
WaitForSpeichermedium -> InputDataForComp: [data != null]\n AND [dataForComp == null]\n AND [analyseTypes contains COMPHEATMAP]
InputDataForComp -d-> WaitForSpeichermedium: getDataForComp()\n [start < end]\n AND [start & end = Date]\n AND [dataType.size == 1]\n AND [data.t == dataForComp.t]
InputDataForComp -> InputDataForComp: getDataForComp()\n [start > end]\n OR [start OR end != Date]\n OR [dataType.size != 1]\n OR [data.t != dataForComp.t]
WaitForSpeichermedium -> Analyse: analyseData()\n [analyseTypes contains COMPHEATMAP]\n AND [data != null] AND [dataForComp != null]\n OR [analyseTypes !contains COMPHEATMAP]\n AND [data != null]

' States
state InputAnalyseTypes: Auswahl Analyse Typen
state InputData: Eingabe benötigter Daten
state WaitForSpeichermedium: Benötigte Daten werden vom Speichermedium besorgt
state InputDataForComp: Eingabe benötigter Daten zum Vergleich
state Analyse: Anmerkung: Verschachtelung der Analysemethoden

@enduml
